### ISSUE TITLE
Repo size is too large - makes builds and testing slow

### ISSUE THREAD

**Issue by marksiemers** [amberframework/amber-spec#5]
There are two main issues making this repo too large:
1. Commit history and pack files (see https://github.com/amberframework/amber/issues/334#issuecomment-340159196 )

The commit history and pack files are fixable, but it means that history will be re-written for this repo (you can see https://github.com/marksiemers/amber-spec/commits/master to see the commit history of a smaller repo (~ 7MB)) - the authors, dates, and commit hashes are the same. It is just the changes in some of the commits are different.

2. Dependency on amber (further questions below)

AFAIK, there are two places that the amber dependency is needed:
- https://github.com/amberframework/amber-spec/blob/master/src/amber_spec.cr#L18
  - This is just a string "application/x-www-form-urlencoded"
- https://github.com/amberframework/amber-spec/blob/master/src/amber_spec.cr#L36
  - This is a Pipe::Pipeline.new

I ask this with pure curiosity - is having this separate library `amber-spec` with a dependency on `amber` worth it? The `amber` generator includes `amber_spec` by default in any new project.

**Comment by marksiemers** [comment]
I'm not familiar enough with the importance of stable commit histories and tags with 0.x versions of open source software, but I do know that the latency of loading this for each `shard install | build | update` is going to deter people.

@drujensen - What are your thoughts on these courses of action:
1. Do nothing - the commit history must remain intact, untouched for this repo
   1. Obviously, no side-effects, but remains an unnecessarily huge repo
1. filter-branch - get the repo size down to ~7MB instead of 30+MB
   1. May have minimal to no side effects as the commit hashes and tags remain, only unnecessary files are removed from history and pack files
1. Minimize repo size - get the repo size down as close to its theoretical minimum as possible (~ 4KB packed - see below)
   1. This is the highest risk highest reward approach, as going from 30MB to 4KB is significant, but it has to be balanced with the cost of losing history and possibly commits

From a brand new git repo that contains only current versions of the files:
```bash
$ git count-objects -vH
count: 0
size: 0 bytes
in-pack: 12
packs: 1
size-pack: 3.76 KiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```

**Comment by faustinoaq** [comment]
> 2. filter-branch - get the repo size down to ~7MB instead of 30+MB
  May have minimal to no side effects as the commit hashes and tags remain, only unnecessary files are removed from history and pack files

I choose the second option 👍 My Internet connection isn't good an `shard install` is taking a lot more in my amber projects 😅 

@marksiemers Thanks you for follow this issue 😄 

@amberframework/contributors WDYT ?

**Comment by marksiemers** [comment]
I wish there was a way to route shard dependencies - then you could do a clean break with an archived repo for existing versions, and a new, small repo going forward.

@faustinoaq - even with a good internet connection, it breaks your workflow. I always have to comment out `shards build` in the test suite, and make sure I don't commit that line.

**Comment by faustinoaq** [comment]
I'm doing some effort to use tags instead of commit,

- https://github.com/amberframework/amber/pull/319 - Fixes some dependencies
- https://github.com/amberframework/amber/issues/333 - Suggested new releases to use tag instead of master branches

I'm also thinking this could be an issue on https://github.com/crystal-lang/shards/issues, because the crystal package manager should just download the specified version instead of cloning the whole repo. WDYT @ysbaddaden ?

**Comment by elorest** [comment]
All of this would be solved if shards didn't download the entire repo. This
is a problem anyway and makes us bad neighbors for Github. Cocoapods ran
into an issue with this when they got large. What we should be doing is
downloading the zip file for branches or tags. These don't contain any
history only the latest files. This is a lot easier and github servers and
bandwidth.

**Comment by faustinoaq** [comment]
@elorest So, Should we minimize repo size as workaround?

**Comment by marksiemers** [comment]
@elorest and @faustinoaq - So this downloading issue needs to be solved here-ish? https://github.com/crystal-lang/shards/blob/ee4087f3c108bd6a1e43295e8b5fb1684335f050/src/resolvers/git.cr#L181

**Comment by elorest** [comment]
Optimally yes. I started working on it but the tests are all written in
Ruby mini test. Which was sort of weird.

**Comment by elorest** [comment]
I was under the impression we were talking about amber and other shards in general. This one has binaries in its history and it makes sense to clean them up with BFG or something IMO.

**Comment by marksiemers** [comment]
I had better luck with `filter-branch` than `bfg`, but I don't have much knowledge or experience with `bfg`. It may be more effective.

I think this thing should be able to get under 1MB (maybe even smaller), but with some work I've already done its at 7MB (in my fork), which is good coming from 30+MB.

**Comment by faustinoaq** [comment]
I think we should delete big files in old commits using `filter-branch` as workaround while shards decides to implement `.cache/shards` or `--download` flag or something similar.

Also benefits people that want to contribute this repo, because cloning 30MB+ is a bit excesive I think

**Comment by marksiemers** [comment]
@faustinoaq - I believe @eliasjpr incorporated changes that got the repo down to ~ 7MB. It was using `filter-branch`

Not sure why we couldn't get it smaller, but still an improvement.

**Comment by marksiemers** [comment]
I think we've done what we can - other than really push for the change to shards.
